# Generated by Django 5.2.5 on 2025-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="содержимое"),
        ),
    ]
