# Generated by Django 5.2.5 on 2025-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Установите флажок для публикации записи на сайте', verbose_name='Опубликован'),
        ),
    ]
